# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---
minimum_pre_commit_version: 1.16.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v3.4.0"
    hooks:
      - id: check-added-large-files
      # - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.1.9"
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  # Format JSON, Markdown and YAML files with Prettier.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        name: Format JSON, Markdown and YAML files
        files: "\\.(\
          json\
          |md|markdown|mdown|mkdn\
          |yaml|yml\
          )$"
        # Do not run on Git push
        stages: [commit]
        verbose: true

    # Format yaml files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.25.0"
    hooks:
      - id: yamllint

  # Configuration defined in .markdownlint.json
  # See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md for configuration options
  - repo: https://github.com/markdownlint/markdownlint
    rev: "v0.11.0"
    hooks:
      - id: markdownlint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: "v4.1.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        verbose: false
