# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---
minimum_pre_commit_version: 1.16.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v3.2.0"
    hooks:
      # - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  # Format JSON, Markdown and YAML files with Prettier.
  - repo: https://github.com/prettier/prettier
    rev: "2.1.2"
    hooks:
      - id: prettier
        name: Format JSON, Markdown and YAML files
        files: "\\.(\
          json\
          |md|markdown|mdown|mkdn\
          |yaml|yml\
          )$"
        # Do not run on Git push
        stages: [commit]
        verbose: true

  # - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
  #   rev: "2.1.0"
  #   hooks:
  #     - id: git-check
  #     - id: git-dirty
  #     - id: markdownlint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: "v3.0.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        verbose: false
